name: Check ADHS Page

on:
  schedule:
    - cron: '0 9 * * *'   # 9 Uhr
    - cron: '0 12 * * *'  # 12 Uhr
    - cron: '0 17 * * *'  # 17 Uhr
  workflow_dispatch: 

jobs:
  check_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_update.py
