name: Check Alexianer Page

on:
  schedule:
    - cron: '0 8 * * *'    # 10 Uhr morgens
    - cron: '0 16 * * *'   # 18 Uhr nachmittags
  workflow_dispatch:       # Manuelles Starten möglich

jobs:
  check_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache last_hash.txt
        uses: actions/cache@v3
        with:
          path: last_hash.txt
          key: last-hash-cache

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_update.py

      - name: Save last_hash.txt to cache
        uses: actions/cache@v3
        with:
          path: last_hash.txt
          key: last-hash-cache
